### PR TITLE
Update README.md

### LINKED ISSUE #20: Modify the readme file in the repo with links to all problem within this repo

### PR DESCRIPTION
**Pull request by muditchoudhary**
Made a table that shows all the problems which are present in this repository.

Closes: #20

### CODE REVIEW

**Comment by saty-a** [comment]
hey there are some issue in merging your pull request

**Comment by muditchoudhary** [comment]
hey, @saty-a resolved the conflicts.

**Comment by saty-a** [comment]
> hey, @saty-a resolved the conflicts.
it shows you added only two spaces nothing else it would be good if you just add that summary table for every problem with links from your previous commits. If you have time then do it, please.

**Review by saty-a — COMMENTED** [review]
all good

**Comment by saty-a** [comment]
Give a star if you like this repo!!

**Pull request merged**
