### PR TITLE
FIX issue #46 :Google Kick Start 2022 Round G  Curling Problem with solution

### PR DESCRIPTION
**Pull request by vaibhv232**
solved    Google Kick Start 2022 Round G  Curling Problem  with best approach

### CODE REVIEW

**Comment by saty-a** [comment]
> solved Google Kick Start 2022 Round G Curling Problem with best approach

Give a star If this repo was helpful

**Comment by vaibhv232** [comment]
@saty-a why your repo is excluded?

**Comment by saty-a** [comment]
> @saty-a why your repo is excluded?

really?

**Comment by saty-a** [comment]
Hey you can contribute here if you want https://github.com/saty-a/Hacktoberfest2022
Just make the pull request in this repo👍

**Comment by vaibhv232** [comment]
> 

yes it is excluded

**Pull request merged**
