### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vani177**
Hey, I've updated the README.md file.

Just sharing, I added the Instagram badge in the social links section because it was there on your github profile, you can remove it if you wish or just update your Instagram page there, I didn't add it because it crashed for me.
image

Hope everything else fits well.
Thanks, that's it!

### CODE REVIEW

**Comment by saty-a** [comment]
give a star if this repo was helpful

**Comment by Vani177** [comment]
> give a star if this repo was helpful

totally, yeah!

Do please add the hacktoberfest-accepted label.

**Comment by saty-a** [comment]
hacktoberfest-accepted label is already present!!

**Comment by Vani177** [comment]
> hacktoberfest-accepted label is already present!!

the thing is that that the issue has not been closed in the issues section where i've been assigned it and so it's not actually added and counted in the prs for hacktoberfest. I hope you understand.
Thanks

**Comment by saty-a** [comment]
can you mention the issue no which were you assigned

**Comment by Vani177** [comment]
> can you mention the issue no which were you assigned

sure, this is it: 
https://github.com/saty-a/Hacktoberfest2022/issues/19

**Comment by saty-a** [comment]
I've closed the issue

**Comment by Vani177** [comment]
> I've closed the issue

thanks a lot and sorry for bothering you again, i think it's this pr that you need to add the labels to...
image

**Pull request merged**
